config/routes.rb
Rails.application.routes.draw do
  resources :quizzes
  devise_for :users
  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :user

  validates :user_id, :title, :presentation, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :quizzes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
    @quiz.user = current_user
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.user = current_user

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:title, :presentation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Squizzes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="alert"><%= alert %></p>
    <p class="notice"><%= notice %></p>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.slim
h1 Pages#home
p Find me in app/views/pages/home.html.slim

app/views/quizzes/_form.html.slim
= form_for @quiz do |f|
  - if @quiz.errors.any?
    #error_explanation
      h2 = "#{pluralize(@quiz.errors.count, "error")} prohibited this quiz from being saved:"
      ul
        - @quiz.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :presentation
    = f.text_area :presentation
  .actions = f.submit

app/views/quizzes/edit.html.slim
h1 Editing quiz

== render 'form'

= link_to 'Show', @quiz
'|
= link_to 'Back', quizzes_path

app/views/quizzes/index.html.slim
h1 Listing quizzes

table
  thead
    tr
      th Title
      th Presentation
      th
      th
      th

  tbody
    - @quizzes.each do |quiz|
      tr
        td = quiz.title
        td = quiz.presentation
        td = link_to 'Show', quiz
        td = link_to 'Edit', edit_quiz_path(quiz)
        td = link_to 'Destroy', quiz, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Quiz', new_quiz_path

app/views/quizzes/new.html.slim
h1 New quiz

== render 'form'

= link_to 'Back', quizzes_path

app/views/quizzes/show.html.slim
p#notice = notice

p
  strong Title:
  = @quiz.title
p
  strong Presentation:
  = @quiz.presentation

= link_to 'Edit', edit_quiz_path(@quiz)
'|
= link_to 'Back', quizzes_path